## Numpy
Mostly used for homogeneous data e.g. floats, ints

In [1]:
import numpy as np

In [2]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
arr.size

16

In [4]:
arr.shape

(16,)

In [5]:
arr.ndim

1

In [6]:
arr2 = arr.reshape(2,8)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
arr2.shape

(2, 8)

In [8]:
arr2[2, 2]   # 10

IndexError: index 2 is out of bounds for axis 0 with size 2

### Moving forward

In [11]:
import numpy as np

arr = np.random.randn(10, 10)
print(arr)
arr = np.round(arr, 2)
print(arr)

[[-1.46017964  1.32724224 -0.83754258  0.53077652 -1.70198102 -0.61955561
   0.66698498  0.32120258  0.60205522  0.17299125]
 [-0.41071358  0.87229068 -0.47986368 -0.40236746 -2.00021113  1.64801858
  -0.54425087  1.07617585 -1.18851607 -0.23064576]
 [-1.04413427 -0.18704464  0.61908976  0.38747027 -0.69551352 -0.3018864
   1.19057911  0.18488837  0.03503561 -1.71910151]
 [ 0.34292087 -0.67126608 -0.3424882  -0.08372475 -0.60055675  0.68601582
  -2.48206602  0.45645422 -0.53966997 -0.23698089]
 [ 0.56177175  0.39283828  0.17817091 -1.33896023 -0.14829798  0.18613195
  -0.3357356   0.30149614 -0.57006525 -0.711158  ]
 [ 0.70791745  0.3165249   0.90795484  0.84075251  0.65355484  0.12094355
  -0.55699935 -1.67204045 -0.67319722  0.38162577]
 [ 0.82421565  1.01703018  0.23995553  0.19788674  0.42472708  1.64284887
   0.3180932   0.57643679  0.14934023 -1.21603725]
 [ 0.51700517 -0.31913468 -0.89940694  1.90421271 -0.52753349 -0.75007602
  -1.7826829   0.18792051  1.18877739 -0.30812993]
 

In [12]:
arr.shape

(10, 10)

In [18]:
arr[1:10:2]

array([[-0.41,  0.87, -0.48, -0.4 , -2.  ,  1.65, -0.54,  1.08, -1.19,
        -0.23],
       [ 0.34, -0.67, -0.34, -0.08, -0.6 ,  0.69, -2.48,  0.46, -0.54,
        -0.24],
       [ 0.71,  0.32,  0.91,  0.84,  0.65,  0.12, -0.56, -1.67, -0.67,
         0.38],
       [ 0.52, -0.32, -0.9 ,  1.9 , -0.53, -0.75, -1.78,  0.19,  1.19,
        -0.31],
       [-0.78,  1.21,  0.67,  1.57, -2.43, -0.04,  0.91, -0.35, -0.97,
        -1.1 ]])

In [19]:
arr[1:10:2,::]  # same as above

array([[-0.41,  0.87, -0.48, -0.4 , -2.  ,  1.65, -0.54,  1.08, -1.19,
        -0.23],
       [ 0.34, -0.67, -0.34, -0.08, -0.6 ,  0.69, -2.48,  0.46, -0.54,
        -0.24],
       [ 0.71,  0.32,  0.91,  0.84,  0.65,  0.12, -0.56, -1.67, -0.67,
         0.38],
       [ 0.52, -0.32, -0.9 ,  1.9 , -0.53, -0.75, -1.78,  0.19,  1.19,
        -0.31],
       [-0.78,  1.21,  0.67,  1.57, -2.43, -0.04,  0.91, -0.35, -0.97,
        -1.1 ]])

In [21]:
arr[1:10:2,0:4] # only 1st 4 columns

array([[-0.41,  0.87, -0.48, -0.4 ],
       [ 0.34, -0.67, -0.34, -0.08],
       [ 0.71,  0.32,  0.91,  0.84],
       [ 0.52, -0.32, -0.9 ,  1.9 ],
       [-0.78,  1.21,  0.67,  1.57]])

Take is that, as we use slicing on lists, we can use that here also, but here it's more effecient. We can specify slicing for each individual array in the array we're dealing with (multi-dimensional).

In [24]:
x = np.array([2,3,5,23,53])
y = np.array([3,32,53,2,43])
np.maximum(x, y)    # element-wise max

array([ 3, 32, 53, 23, 53])

In [25]:
x * y

array([   6,   96,  265,   46, 2279])

In [28]:
x2 = np.arange(9).reshape(3, 3)
y2 = np.arange(9).reshape(3, 3)
print(x2, "\n\n", y2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
x2*y2 # element-wise

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [31]:
# for dot product
np.dot(x2,y2)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [32]:
x2_b = np.arange(6).reshape(3,2)
x2_b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
# x2 * x2_b   # will fail because element-wise calcs are not possible

np.dot(x2, x2_b)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [36]:
x2.dot(x2_b)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [40]:
print(x2)
x2_t = x2.T

print("\nTransposed: \n", x2_t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Transposed: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


In [41]:
x2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
# when 2nd dimension is unknown/unconsidered
x2_b.shape

(3, 2)

In [50]:
x2_b.reshape(2, -1)

array([[0, 1, 2],
       [3, 4, 5]])

#### Concatenate

In [52]:
print(x2, "\n\n", x2_b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[0 1]
 [2 3]
 [4 5]]


In [53]:
np.concatenate((x2, x2_b), axis=1)

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [55]:
# can also do
np.hstack((x2, x2_b))

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [61]:
print(x2, "\n\n", y2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
np.vstack((x2, y2))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- For hstack, num of rows should be same.
- For vstack, num of cols should be same.

## Pandas
Mostly used for heterogeneous data.